#command to create the database
#create database guestadmin;

#command to create a user for the webapplication to read write. Use the 41 byte password encryption.
#CREATE USER 'appadmin'@'localhost' IDENTIFIED BY PASSWORD '*XXXXXXXXXXXXXXXXXX';

#assign permissions to application user
#GRANT SELECT, INSERT, UPDATE, DELETE ON guestadmin.* TO 'appadmin'@'localhost';


create table GTUSERINFO ( USERINFOID VARCHAR(45) NOT NULL, FIRST_NAME VARCHAR(256) NOT NULL, LAST_NAME VARCHAR(256), ADDRESS_1 VARCHAR(1024) , ADDRESS_2 VARCHAR(1024), CITY VARCHAR(1024), STATE VARCHAR(30), COUNTRY VARCHAR(45), IP_ADDRESS VARCHAR(1024), CELL_PHONE VARCHAR(15), PHONE_NUM VARCHAR(15), EMAIL VARCHAR(100), IS_TMP INT(1) NOT NULL DEFAULT 1 , DEL_ROW INT(1) NOT NULL DEFAULT 0,CREATEDATE BIGINT(20) NOT NULL DEFAULT 0, PRIMARY KEY (USERINFOID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8; 

create table GTADMIN ( ADMINID VARCHAR(45) NOT NULL, FK_USERINFOID VARCHAR(45) NOT NULL, CREATEDATE  BIGINT(20) NOT NULL DEFAULT 0,IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0 , PRIMARY KEY (ADMINID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;

create table GTGUESTS ( GUESTID VARCHAR(45) NOT NULL, FK_USERINFOID VARCHAR(45) NOT NULL , FK_ADMINID VARCHAR(45) NOT NULL, CREATEDATE  BIGINT(20) NOT NULL DEFAULT 0 , TOTAL_SEATS INT(11) NOT NULL DEFAULT 1, IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (GUESTID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;


create table GTTABLE (TABLEID VARCHAR(45) NOT NULL, TABLENAME VARCHAR(1024), TABLENUM INT(11), NUMOFSEATS INT(11) NOT NULL DEFAULT 1 , IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, CREATEDATE  BIGINT(20) NOT NULL DEFAULT 0 , FK_ADMINID VARCHAR(45) NOT NULL , MODIFYDATE BIGINT(20) NOT NULL DEFAULT 0, MODIFIEDBY VARCHAR(45) NOT NULL, PRIMARY KEY (TABLEID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8; 

create table GTFOLDER ( FOLDERID VARCHAR(45) NOT NULL, FOLDERNAME VARCHAR(1024), PARENT_FOLDERID VARCHAR(45), IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, CREATEDATE  BIGINT(20) NOT NULL DEFAULT 0, PRIMARY KEY (FOLDERID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8; 

create table GTEVENT (EVENTID VARCHAR(45) NOT NULL, EVENTNUM INT(11) NOT NULL AUTO_INCREMENT , EVENTNAME VARCHAR(2048) NOT NULL DEFAULT 'New Event', FK_FOLDERID VARCHAR(45) NOT NULL, CREATEDATE BIGINT(20) NOT NULL DEFAULT 0 , FK_ADMINID VARCHAR(45) NOT NULL, IS_TMP INT(1) NOT NULL DEFAULT 1 , DEL_ROW INT(1) NOT NULL DEFAULT 0,  PRIMARY KEY (EVENTNUM) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;

create table GTEVENTTABLES ( EVENTTABLEID  VARCHAR(45) NOT NULL, FK_EVENTID VARCHAR(45) NOT NULL, FK_TABLEID VARCHAR(45) NOT NULL , ASSIGN_TO_EVENT INT(1) NOT NULL DEFAULT 0, IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (EVENTTABLEID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8; 

create table GTTABLEGUESTS ( TABLEGUESTID  VARCHAR(45) NOT NULL, FK_TABLEID VARCHAR(45) NOT NULL ,  FK_GUESTID VARCHAR(45) NOT NULL, IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (TABLEGUESTID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8; 

create table GTEVENTGUESTS ( EVENTGUESTID VARCHAR(45) NOT NULL, FK_EVENTID VARCHAR(45) NOT NULL, FK_GUESTID VARCHAR(45) NOT NULL, IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (EVENTGUESTID) )  ENGINE = MyISAM DEFAULT CHARSET = utf8; 

ALTER TABLE GTUSERINFO ADD COLUMN HUMAN_CREATEDATE VARCHAR(45) NULL ;
ALTER TABLE GTTABLE ADD COLUMN HUMAN_CREATEDATE VARCHAR(50) NULL , ADD COLUMN HUMAN_MODIFYDATE VARCHAR(45) NULL ;
ALTER TABLE GTTABLEGUESTS ADD COLUMN ASSIGNED_SEATS INT(11) NOT NULL DEFAULT 0  AFTER DEL_ROW ;
ALTER TABLE GTGUESTS ADD COLUMN RSVP_SEATS INT(11) DEFAULT -1;
ALTER TABLE GTEVENT ADD COLUMN EVENTDATE BIGINT(20) NOT NULL DEFAULT 0;
ALTER TABLE GTUSERINFO ADD COLUMN TIMEZONE VARCHAR(15) NOT NULL;

#Indexes

ALTER TABLE GTEVENT ADD INDEX EVENT_ID (EVENTID ASC) ;



#create table GTADMINGUESTS ( ADMINGUESTID VARCHAR(45) NOT NULL,  FK_ADMINID VARCHAR(45) NOT NULL, FK_GUESTID VARCHAR(45), CREATEDATE  BIGINT(20) NOT NULL DEFAULT 0 , IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (ADMINGUESTID) ) ENGINE = MyISAM DEFAULT #CHARSET = utf8;



