#Query to update a number for the event

#update GTTELNUMBERS SET TELNUMBER = '14155992671', FK_EVENTID='8f337e98-714e-4249-b1e0-aeed47741b7c',FK_ADMINID='11d12027-e1b2-495b-8f74-ab5a16a3cd0c' WHERE TELNUMBERID='0b5d55ae-049f-4ec9-906a-a11b58dd4be7';


#command to create the database
#create database guestadmin;

#create the password encrypted 41 byte password
#select password('FD3C08EEE89__________');

#command to create a user for the webapplication to read write. Use the 41 byte password encryption.
#CREATE USER 'appadmin'@'localhost' IDENTIFIED BY PASSWORD '*XXXXXXXXXXXXXXXXXX';

#assign permissions to application user
#GRANT SELECT, INSERT, UPDATE, DELETE ON guestadmin.* TO 'appadmin'@'localhost';

create table GTUSERINFO ( USERINFOID VARCHAR(45) NOT NULL, FIRST_NAME VARCHAR(256) NOT NULL, LAST_NAME VARCHAR(256), ADDRESS_1 VARCHAR(1024) , ADDRESS_2 VARCHAR(1024), CITY VARCHAR(1024), STATE VARCHAR(30), COUNTRY VARCHAR(45), IP_ADDRESS VARCHAR(1024), CELL_PHONE VARCHAR(15), PHONE_NUM VARCHAR(15), EMAIL VARCHAR(100), IS_TMP INT(1) NOT NULL DEFAULT 1 , DEL_ROW INT(1) NOT NULL DEFAULT 0,CREATEDATE BIGINT(20) NOT NULL DEFAULT 0, PRIMARY KEY (USERINFOID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8; 
create table GTADMIN ( ADMINID VARCHAR(45) NOT NULL, FK_USERINFOID VARCHAR(45) NOT NULL, CREATEDATE BIGINT(20) NOT NULL DEFAULT 0,IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0 , PRIMARY KEY (ADMINID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
create table GTGUESTS ( GUESTID VARCHAR(45) NOT NULL, FK_USERINFOID VARCHAR(45) NOT NULL , FK_ADMINID VARCHAR(45) NOT NULL, CREATEDATE BIGINT(20) NOT NULL DEFAULT 0 , TOTAL_SEATS INT(11) NOT NULL DEFAULT 1, IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (GUESTID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
create table GTTABLE (TABLEID VARCHAR(45) NOT NULL, TABLENAME VARCHAR(1024), TABLENUM INT(11), NUMOFSEATS INT(11) NOT NULL DEFAULT 1 , IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, CREATEDATE BIGINT(20) NOT NULL DEFAULT 0 , FK_ADMINID VARCHAR(45) NOT NULL , MODIFYDATE BIGINT(20) NOT NULL DEFAULT 0, MODIFIEDBY VARCHAR(45) NOT NULL, PRIMARY KEY (TABLEID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8; 
create table GTFOLDER ( FOLDERID VARCHAR(45) NOT NULL, FOLDERNAME VARCHAR(1024), PARENT_FOLDERID VARCHAR(45), IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, CREATEDATE BIGINT(20) NOT NULL DEFAULT 0, PRIMARY KEY (FOLDERID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8; 
create table GTEVENT (EVENTID VARCHAR(45) NOT NULL, EVENTNUM INT(11) NOT NULL AUTO_INCREMENT , EVENTNAME VARCHAR(2048) NOT NULL DEFAULT 'New Event', FK_FOLDERID VARCHAR(45) NOT NULL, CREATEDATE BIGINT(20) NOT NULL DEFAULT 0 , FK_ADMINID VARCHAR(45) NOT NULL, IS_TMP INT(1) NOT NULL DEFAULT 1 , DEL_ROW INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (EVENTNUM) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
create table GTEVENTTABLES ( EVENTTABLEID VARCHAR(45) NOT NULL, FK_EVENTID VARCHAR(45) NOT NULL, FK_TABLEID VARCHAR(45) NOT NULL , ASSIGN_TO_EVENT INT(1) NOT NULL DEFAULT 0, IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (EVENTTABLEID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8; 
create table GTTABLEGUESTS ( TABLEGUESTID VARCHAR(45) NOT NULL, FK_TABLEID VARCHAR(45) NOT NULL , FK_GUESTID VARCHAR(45) NOT NULL, IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (TABLEGUESTID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8; 
create table GTEVENTGUESTS ( EVENTGUESTID VARCHAR(45) NOT NULL, FK_EVENTID VARCHAR(45) NOT NULL, FK_GUESTID VARCHAR(45) NOT NULL, IS_TMP INT(1) NOT NULL DEFAULT 1, DEL_ROW INT(1) NOT NULL DEFAULT 0,TOTAL_INVITED_SEATS INT(11), RSVP_SEATS INT(11), PRIMARY KEY (EVENTGUESTID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8; 
ALTER TABLE GTUSERINFO ADD COLUMN HUMAN_CREATEDATE VARCHAR(45) NULL ;
ALTER TABLE GTTABLE ADD COLUMN HUMAN_CREATEDATE VARCHAR(50) NULL;
ALTER TABLE GTTABLE ADD COLUMN HUMAN_MODIFYDATE VARCHAR(45) NULL;
ALTER TABLE GTTABLEGUESTS ADD COLUMN ASSIGNED_SEATS INT(11) NOT NULL DEFAULT 0 AFTER DEL_ROW ;
ALTER TABLE GTGUESTS ADD COLUMN RSVP_SEATS INT(11) DEFAULT -1;
ALTER TABLE GTEVENT ADD COLUMN EVENTDATE BIGINT(20) NOT NULL DEFAULT 0;
ALTER TABLE GTUSERINFO ADD COLUMN TIMEZONE VARCHAR(15) NOT NULL;
ALTER TABLE GTGUESTS ADD COLUMN HUMANCREATEDATE VARCHAR(45) NOT NULL;
ALTER TABLE GTADMIN ADD COLUMN HUMANCREATEDATE VARCHAR(45) NOT NULL;
ALTER TABLE GTEVENT ADD COLUMN HUMANCREATEDATE VARCHAR(45) NOT NULL;
ALTER TABLE GTEVENT ADD COLUMN HUMANEVENTDATE VARCHAR(45) NOT NULL;
create table GTTELNUMBERS ( TELNUMBERID VARCHAR(45) NOT NULL, TELNUMBER VARCHAR(45) NOT NULL, FK_TELNUMBERTYPEID VARCHAR(45) NOT NULL, FK_EVENTID VARCHAR(45) NOT NULL, FK_ADMINID VARCHAR(45) NOT NULL , DEL_ROW INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (TELNUMBERID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
create table GTTELNUMBERTYPE (TELNUMBERTYPEID VARCHAR(45) NOT NULL, DESCRIPTION TEXT, TELNUMTYPE VARCHAR(45) NOT NULL, PRIMARY KEY (TELNUMBERTYPEID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
create table GTINCOMINGCALL (INCOMINGCALLID VARCHAR(45) NOT NULL, GUESTS_TELNUMBER VARCHAR(45) NOT NULL, CALLED_TELNUMBER VARCHAR(45) NOT NULL, CREATEDATE BIGINT(20) NOT NULL DEFAULT 0, HUMANCREATEDATE VARCHAR(45), PRIMARY KEY (INCOMINGCALLID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
create table GTGUESTINCOMINGCALLS ( GUESTINCOMINGCALLID VARCHAR(45) NOT NULL, FK_INCOMINGCALLID VARCHAR(45) NOT NULL, FK_GUESTID VARCHAR(45) NOT NULL, FK_EVENTID VARCHAR(45), FK_ADMINID VARCHAR(45), CALL_STATUS VARCHAR(45) NOT NULL, CALL_ACTION VARCHAR(45) NOT NULL DEFAULT 'DO_NOTHING',PRIMARY KEY (GUESTINCOMINGCALLID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
create table GTORPHANINCOMINGCALLS ( ORPHANINCOMINGCALLID VARCHAR(45) NOT NULL, FK_INCOMINGCALLID VARCHAR(45) NOT NULL, CALL_STATUS VARCHAR(45) NOT NULL, CALL_ACTION VARCHAR(45) NOT NULL DEFAULT 'DO_NOTHING' , PRIMARY KEY (ORPHANINCOMINGCALLID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
insert into GTTELNUMBERTYPE (TELNUMBERTYPEID,DESCRIPTION,TELNUMTYPE) VALUES ('bb6f4f95-1a09-4f4c-9913-3f9ae04457fa','Rsvp Telephone Number','RSVP_TEL');insert into GTTELNUMBERTYPE (TELNUMBERTYPEID,DESCRIPTION,TELNUMTYPE) VALUES ('6041479d-8a47-4a85-bb6e-5d31f786ca13','Seating Telephone Number','SEATING_TEL');
create table GTPASSWORD ( PASSWORDID VARCHAR(45) NOT NULL, PASSWORD VARCHAR(75) NOT NULL, FK_ADMINID VARCHAR(45) NOT NULL, CREATEDATE BIGINT(20) NOT NULL DEFAULT 0, HUMANCREATEDATE VARCHAR(45) , PASSWORD_STATUS VARCHAR(5) NOT NULL, PRIMARY KEY (PASSWORDID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
create table GTADMINTELEPHONYACCOUNT ( ADMINTELEPHONYACCOUNT VARCHAR(45) NOT NULL, FK_ADMINID VARCHAR(45) NOT NULL, ACCOUNTSID VARCHAR(45) NOT NULL, AUTH_TOKEN VARCHAR(45) NOT NULL , DEL_ROW INT(1) NOT NULL DEFAULT 0 ,CREATEDATE BIGINT(20) NOT NULL DEFAULT 0, HUMANCREATEDATE VARCHAR(45), PRIMARY KEY (ADMINTELEPHONYACCOUNT) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
ALTER TABLE GTTELNUMBERS ADD COLUMN IS_ACTIVE INT(1) DEFAULT 0, ADD COLUMN IS_PURCHASED INT(1) DEFAULT 0;
create table GTPRICEGROUP ( PRICEGROUPID VARCHAR(45) NOT NULL, PRICEGROUPNAME VARCHAR(45) NOT NULL, MIN_GUEST_NUM INT(10) NOT NULL DEFAULT 0, MAX_GUEST_NUM INT(10) NOT NULL DEFAULT 0,PRICE DECIMAL(10,2) NOT NULL, PRIMARY KEY (PRICEGROUPID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
create table GTEVENTPRICEGROUP ( EVENTPRICEGROUPID VARCHAR(45) NOT NULL, FK_ADMINID VARCHAR(45) NOT NULL, FK_EVENTID VARCHAR(45) NOT NULL, FK_PRICEGROUPID VARCHAR(45) NOT NULL, PURCHASE_COMPLETE INT(1) NOT NULL DEFAULT 0, PRIMARY KEY (EVENTPRICEGROUPID) )ENGINE = MyISAM DEFAULT CHARSET = utf8;
insert into GTPRICEGROUP (PRICEGROUPID,PRICEGROUPNAME,MIN_GUEST_NUM,MAX_GUEST_NUM) VALUES ('f64e4d1e-5dd2-11e1-a697-592f61e300d6','Minimum pricing group',0,50);
insert into GTPRICEGROUP (PRICEGROUPID,PRICEGROUPNAME,MIN_GUEST_NUM,MAX_GUEST_NUM) VALUES ('7f55012a-5dd3-11e1-bfe5-304562ecd4d0','Basic pricing group',51,150);
insert into GTPRICEGROUP (PRICEGROUPID,PRICEGROUPNAME,MIN_GUEST_NUM,MAX_GUEST_NUM) VALUES ('a976e446-5dd3-11e1-bf5a-452f61e300d6','Maximum pricing group',151,300);
create table GTBILLADDRESS ( BILLADDRESSID VARCHAR(45) NOT NULL, FK_ADMINID VARCHAR(45) NOT NULL, FK_EVENTID VARCHAR(45) NOT NULL, FIRSTNAME VARCHAR(400) NOT NULL,MIDDLENAME VARCHAR(400), LASTNAME VARCHAR(400) NOT NULL, ADDRESS1 VARCHAR(400) NOT NULL, ADDRESS2 VARCHAR(400) NOT NULL, CITY VARCHAR(400) NOT NULL, ZIP VARCHAR(15) NOT NULL, STATE VARCHAR(400) NOT NULL, COUNTRY VARCHAR(400) NOT NULL, PRIMARY KEY (BILLADDRESSID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
create table GTBILLCREDITCARD ( BILLCREDITCARDID VARCHAR(45) NOT NULL,FK_BILLADDRESSID VARCHAR(45) NOT NULL, FK_ADMINID VARCHAR(45) NOT NULL, FK_EVENTID VARCHAR(45) NOT NULL, CREDITCARDNUM VARCHAR(45) NOT NULL, SECURITYCODE VARCHAR(10) NOT NULL, AMOUNT DECIMAL (10,2) NOT NULL, PRIMARY KEY (BILLCREDITCARDID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
ALTER TABLE GTEVENT ADD INDEX EVENT_ID (EVENTID ASC) ;
create table GTEMAILQUEUE ( EMAILQUEUEID VARCHAR(45) NOT NULL, FROM_ADDRESS VARCHAR(256) NOT NULL,FROM_ADDRESS_NAME VARCHAR(256), TO_ADDRESS VARCHAR(256) NOT NULL,TO_ADDRESS_NAME VARCHAR(256), EMAIL_SUBJECT TEXT, HTML_BODY TEXT NOT NULL, TEXT_BODY TEXT NOT NULL, STATUS VARCHAR(10) NOT NULL, CREATEDATE BIGINT(20) NOT NULL DEFAULT 0, MODIFIEDDATE BIGINT(20) NOT NULL DEFAULT 0, HUMANCREATEDATE VARCHAR(45), HUMANMODIFYDATE VARCHAR(45), PRIMARY KEY (EMAILQUEUEID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
create table GTEMAILTEMPLATE( EMAILTEMPLATEID VARCHAR(45) NOT NULL, EMAILTEMPLATENAME VARCHAR(20) NOT NULL, FROM_ADDRESS_NAME VARCHAR(256) NOT NULL, FROM_EMAIL_ADDRESS VARCHAR(256) NOT NULL, TO_ADDRESS_NAME VARCHAR(256) , TO_EMAIL_ADDRESS VARCHAR(256), EMAIL_SUBJECT TEXT, HTML_BODY TEXT NOT NULL, TEXT_BODY TEXT NOT NULL, PRIMARY KEY (EMAILTEMPLATEID) ) ENGINE = MyISAM DEFAULT CHARSET = utf8;
INSERT INTO GTEMAILTEMPLATE ( EMAILTEMPLATEID, EMAILTEMPLATENAME, FROM_ADDRESS_NAME, FROM_EMAIL_ADDRESS, EMAIL_SUBJECT , HTML_BODY, TEXT_BODY ) VALUES ( '21f93eb0-8367-11e1-b99c-78f135b03cf1', 'REGISTRATION', 'Guest Seater', 'kjwork18@gmail.com','User Registered', 'Thank you for registering<br><br>__USERNAME__','Thank you for registering\n\n__USERNAME__');